name: Build & Deploy Strapi

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: strapi-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # ✅ Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # ✅ Create infra FIRST (ECR, ECS, VPC, IAM)
    - name: Terraform Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

    # ✅ Now login to ECR (repo exists)
    - name: Login to ECR
      run: |
        aws ecr get-login-password \
        | docker login --username AWS --password-stdin \
        $(aws ecr describe-repositories --repository-names $ECR_REPOSITORY --query 'repositories[0].repositoryUri' --output text)

    # ✅ Build & Push image
    - name: Build & Push Image
      run: |
        REPO_URI=$(aws ecr describe-repositories --repository-names $ECR_REPOSITORY --query 'repositories[0].repositoryUri' --output text)
        IMAGE_TAG=${{ github.sha }}

        docker build -t $REPO_URI:$IMAGE_TAG ./app
        docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest

        docker push $REPO_URI:$IMAGE_TAG
        docker push $REPO_URI:latest

